### ISSUE TITLE
Unable to compose docker container

### ISSUE THREAD

**Issue by jdchart** [SCENE-CE/mirador-multi-user#22]
Hello, when running `docker-compose up --build` I appear to be having troubles with the front end, I get the following error:

```bash
mirador-multi-user-frontend-1  | sh: PROD: unknown operand
mirador-multi-user-frontend-1  | Starting the application in dev mode
mirador-multi-user-frontend-1  | 
mirador-multi-user-frontend-1  | > mmu-front-end@0.0.0 dev
mirador-multi-user-frontend-1  | > vite --host
mirador-multi-user-frontend-1  | 
mirador-multi-user-frontend-1  | 
mirador-multi-user-frontend-1  | /app/node_modules/rollup/dist/native.js:59
mirador-multi-user-frontend-1  |                throw new Error(
mirador-multi-user-frontend-1  |                      ^
mirador-multi-user-frontend-1  | 
mirador-multi-user-frontend-1  | Error: Cannot find module @rollup/rollup-linux-arm64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
mirador-multi-user-frontend-1  |     at requireWithFriendlyError (/app/node_modules/rollup/dist/native.js:59:9)
mirador-multi-user-frontend-1  |     at Object.<anonymous> (/app/node_modules/rollup/dist/native.js:68:76)
mirador-multi-user-frontend-1  |     ... 3 lines matching cause stack trace ...
mirador-multi-user-frontend-1  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
mirador-multi-user-frontend-1  |     at cjsLoader (node:internal/modules/esm/translators:348:17)
mirador-multi-user-frontend-1  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
mirador-multi-user-frontend-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
mirador-multi-user-frontend-1  |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
mirador-multi-user-frontend-1  |   [cause]: Error: Cannot find module '@rollup/rollup-linux-arm64-musl'
mirador-multi-user-frontend-1  |   Require stack:
mirador-multi-user-frontend-1  |   - /app/node_modules/rollup/dist/native.js
mirador-multi-user-frontend-1  |       at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
mirador-multi-user-frontend-1  |       at Module._load (node:internal/modules/cjs/loader:986:27)
mirador-multi-user-frontend-1  |       at Module.require (node:internal/modules/cjs/loader:1233:19)
mirador-multi-user-frontend-1  |       at require (node:internal/modules/helpers:179:18)
mirador-multi-user-frontend-1  |       at requireWithFriendlyError (/app/node_modules/rollup/dist/native.js:41:10)
mirador-multi-user-frontend-1  |       at Object.<anonymous> (/app/node_modules/rollup/dist/native.js:68:76)
mirador-multi-user-frontend-1  |       at Module._compile (node:internal/modules/cjs/loader:1358:14)
mirador-multi-user-frontend-1  |       at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
mirador-multi-user-frontend-1  |       at Module.load (node:internal/modules/cjs/loader:1208:32)
mirador-multi-user-frontend-1  |       at Module._load (node:internal/modules/cjs/loader:1024:12) {
mirador-multi-user-frontend-1  |     code: 'MODULE_NOT_FOUND',
mirador-multi-user-frontend-1  |     requireStack: [ '/app/node_modules/rollup/dist/native.js' ]
mirador-multi-user-frontend-1  |   }
mirador-multi-user-frontend-1  | }
mirador-multi-user-frontend-1  | 
mirador-multi-user-frontend-1  | Node.js v20.13.1
mirador-multi-user-frontend-1  | 
mirador-multi-user-frontend-1 exited with code 1
```

After looking online I tried deleting the `package-lock.json` file and node_modules in `frontend-TS`, no luck. 

FYI when unning `npm install` for the front end i get the following warnings:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies

added 879 packages, and audited 880 packages in 36s

119 packages are looking for funding
  run `npm fund` for details

17 vulnerabilities (3 moderate, 11 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

```
Back end and db all appear to be working fine. I'm on a Mac M2 2022.

Cheers!

**Comment by geourjoa** [comment]
Hi Jacob !

Sorry if the deployment don't works ...
It seems to be related of ARM architecture of M2 

A beginning of solution : 
https://github.com/rollup/rollup/issues/5194#issuecomment-1833271025

I have deployed an MMU instance on our server : https://arvest.tetras-libre.fr 

For now it have some limitations : 
- No mail configuration, so you can't use forgotten password or thing like that
- Some buttons are inactive. 
- Bad session management. --> clear your cookies and comeback on " https://arvest.tetras-libre.fr " will be your best solution

I'm currently trying to improve that

**Comment by jdchart** [comment]
H! !

Thanks for looking into this, I'll look into the rollup issue tonight (in the train).

Just taken a look at the instance and it's looking great! Will start tinkering tonight!
